[package]
name = "avalanched-aws"
version = "0.0.10-pre"
edition = "2021"
rust-version = "1.62"

[[bin]]
name = "avalanched-aws"
path = "src/main.rs"

[dependencies]
avalanche-sdk = { version = "0.0.10", features = ["cloudwatch"] }
avalanche-types = { version = "0.0.17", features = ["jsonrpc", "metrics"] }
avalanche-utils = { version = "0.0.6", features = ["full"] }
avalanchego = { path = "../../avalanchego" }
avalancheup-aws = { path = "../../bin/avalancheup-aws" }
aws-sdk-cloudwatch = "0.15.0"
aws-sdk-manager = "0.0.6"
aws-sdk-s3 = "0.15.0"
clap = { version = "3.2.8", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
env_logger = "0.9.0"
log = "0.4.17"
tempfile = "3.3.0"
tokio = { version = "1.19.2", features = ["full"] }
