[package]
name = "coreth"
version = "0.0.1"
edition = "2021"

[dependencies]
log = "0.4.16"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

[dev-dependencies]
env_logger = "0.9.0"
